### ISSUE TITLE
Duplicate module provider

### ISSUE THREAD

**Issue by thierrymarianne** [GertjanReynaert/react-native-device#1]
After having installed `react-native-device` with `react-native@0.4.0`, the following error has been raised by flow 

```
~/myapp/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js: ActionSheetIOS
Duplicate module provider
  ~/myapp/node_modules/react-native-device/node_modules/react-native/Libraries/ActionSheetIOS/ActionSheetIOS.js: current provider
```

Same kind of error goes for all other providers. There seem to be some overlap with the libraries covered by `flow`.

I thought maybe you would have some clue about how to fix this?

**Comment by GertjanReynaert** [comment]
@thierrymarianne sorry for the late response.
My package wasn't updated to RN 0.4.0 so that could have been the issue. I updated the package (not yet pushed to NPM) so could you give that a try? (Just install using the github url instead of the module name.) 

If this doesn't help, can you give me some steps for how I could reproduce this issue? Until now I've never used Flow, so that's a bit of an unknown area for me.

**Comment by GertjanReynaert** [comment]
@thierrymarianne I just updated the package on npm, so installing the 0.2.0 version should give you the latest version.

**Comment by thierrymarianne** [comment]
Thank you @GertjanReynaert! Sorry for not having replied earlier.
