### ISSUE TITLE
Update NPM Package & Description

### ISSUE THREAD

**Issue by kkjdaniel** [GertjanReynaert/react-native-device#12]
Currently NPM doesn't reflect the NPM package, I've updated the `package.json` so should just be a case of pulling and publishing.

Also I think it may be a good idea to change the repo description to reflect the updated features, something along the lines of "A wrapper for the native UIDevice Class"?

Thanks,
Karl

**Comment by GertjanReynaert** [comment]
@kkjdaniel Just published the latest version of the package to NPM.

**Comment by GertjanReynaert** [comment]
@kkjdaniel I updated the description to `A UIDevice class wrapper for React Native`, I also updated the readme so the top title is the same as the name of the npm package, since the description below it already clearly explains that this package wraps the UIDevice class.

Please reopen if you disagree with something.

**Comment by kkjdaniel** [comment]
Yeah that's fine, all good now, thanks!
