### ISSUE TITLE
[Suggestion] Using the UIDevice class

### ISSUE THREAD

**Issue by paramaggarwal** [GertjanReynaert/react-native-device#3]
Ideally given the use case for detecting the device, you'd want to use [UIDevice](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/index.html#//apple_ref/occ/instp/UIDevice/model), right? Moving to it would be a pretty big shift for the entire repo, but will keep the library relevant when new devices come out. It also fits in with the name of the repo itself. What do you think?

Imagine exposing all of this in JS: [GBDeviceInfo](https://github.com/lmirosevic/GBDeviceInfo)

**Comment by GertjanReynaert** [comment]
@paramaggarwal Great suggestion, Since facebook uses [UIScreen](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScreen_Class/) for the dimensions I currently use, I was thinking of combining both `UIScreen` and `UIDevice`.

However since my knowledge of objective-c (and integrating it with react native) is pretty basic, this could take a while.

Any help (hints or pr's) are definitely welcome.

**Comment by pickhardt** [comment]
I agree. That's how I found this repo, in fact. I am looking for the full name of the device (e.g. "John Smith's iPhone" If you could pass through the values from UIDevice that would fit with what I expected the repo to do. Any UIScreen stuff is a nice bonus.

**Comment by kkjdaniel** [comment]
#11
